vue/control.vue
vue/info.vue

on off fix

---

vue/control.vue
vue/info.vue

Correctly fetching `devices.json` from webApp root.

Fix devices.json fetch

---

vue/ota.vue

Addressed https://github.com/openshwprojects/OpenBK7231T_App/issues/197

Check chipset

---

devices.json

A60 Bulb, Casenl 4 gang switch & MOES 4gang

Add new devices

---

devices.json

Add MagicHome CCT : ZJ-BWCE-CCT v1.1

Add MagicHome CCT : ZJ-BWCE-CCT v1.1

---

devices.json

https://www.elektroda.com/rtvforum/viewtopic.php?p=20249291#20249291

Add BL0397 version of Elivco LSPA9 plug

---

devices.json

Tested on Aliexpress devices: https://www.aliexpress.com/item/1005002740558678.html
Obsoletes https://github.com/openshwprojects/OpenBK7231T_App/pull/373.

Add Aubess A5C-30E1-02 pin config variant

---

devices.json

* Corrected Pin 7 to use PWM_n instead of PWM.
* Added correct vendor.
* Updated image to use a better representation (note: I also updated the forum/wiki post as well)

Updated SHOP/4/HO/CCT/AG with corrections

---

vue/ota.vue

Added header content check based on `tls_fwup_img_header_check` which checks the first 4 bytes for special value.
https://github.com/openshwprojects/OpenW600/blob/bd11804c91e06194f2a875ea62037fa1d5fae8ed/platform/common/fwup/wm_fwup.c#L71

Added firmware check

---

devices.json

Add MS-104D device to devices.json

Add MS-104D device

---

devices.json

I also linted/formatted the file.
I have GPIO pinouts for this: https://www.amazon.com/gp/product/B0B5G6MDQ6 as well but didn't bother with keeping the BK module so I didn't test. I swapped in an ESP-12f module and the pinouts that I do have are working with Tastmota/ESPHome, though.
If you want me to include an un-tested json document for it, let me know.

Add BN-Link U158WT

---

devices.json

Add support for LVWIT RGBCW from Amazon.co.uk.
Link to buy: https://www.amazon.co.uk/dp/B083DNGQKD

Add support for LVWIT RGBCW

---

devices.json

Adding pins configuration for SHT3X Driver and Battery calculation

add pins for SHT30 Sensor

---

devices.json

Tested with an device flashed by tuya-cloudcutter - Also added an teardown here: https://www.elektroda.com/rtvforum/viewtopic.php?p=20420773#20420773

Added Hama WiFi LED Filament, E27, 00176587

---

devices.json

Adding config for Freshing RGBW bulb as described in my teardown : https://www.elektroda.com/rtvforum/topic3954346.html

Adding to devices.json for Freshin RGBW light bulb

---

devices.json

I haven't tested this (I don't know how) but I I believe this is correct.
I added two product for the same device so people can find them easier.
https://www.elektroda.com/rtvforum/topic3969247.html

devices: Add LSH-B22RGB10W and CSH-B22RGB10W

---

devices.json

Config for Arlec Grid Connect PC192HA Plug-In Socket With USB

Config for Arlec PC192HA

---

vue/control.vue

Fix PWM_n slider not being shown in the configuration

Status page fix

---

devices.json

Teardown: https://www.elektroda.com/rtvforum/topic3973761.html

Adding Novostella 25W RGB Flood lights

---

devices.json

- Add Calex ST64 led lightbulb - [Teardown](https://www.elektroda.com/rtvforum/topic3982014.html)
- Add Calex G125 led lightbulb - [Teardown](https://www.elektroda.com/rtvforum/topic3982011.html)

Add Calex ST64/G125 lighbulbs

---

devices.json

adds Globe 50278
Sorry for the closed pull req - GitHub is not my strong suit.

Add Globe Electric 50278 RGB Strip

---

devices.json

Added device info to devices.json

Add device Minoston MT10W countdown timer switch

---

devices.json

Added the JSON config of new device called "ONENUO Tuya Wifi Magnetic Door Sensor".
See topic on elektroda:
https://www.elektroda.com/rtvforum/viewtopic.php?p=20896810#20896810

New device Onenuo 19JWT

---

devices.json

This PR adds a new device to the list. Check out the [forum post](https://www.elektroda.com/rtvforum/viewtopic.php?p=20863828#20863828) if you're interested.

Add SK26 Smart LED Galaxy Projector

---

devices.json

threads checked to confirm presence of BL0942 chip

add startdriver bl0942 command to 3 devices

---

vue/ota.vue

fix LN OTA postfix

---

devices.json

https://www.elektroda.com/rtvforum/viewtopic.php?p=21052849#21052849

add PCB text keywords. change board to T34 to match other

---

devices.json

Add use for the reset button, and reduce short button press delay.

Update devices.json (Kasa Light Switch, use reset button)

---

devices.json

The box pictures themselves show 2700K, I have these bulbs, same box.

Fix color range for a couple Tuya devices
